[phases.setup]
nixPkgs = ["nodejs_20", "openssl"]

[phases.install]
cmds = ["npm install -g pnpm@9 && ln -sf $(npm prefix -g)/bin/pnpm /usr/bin/pnpm && pnpm install --no-frozen-lockfile"]

[phases.build]
cmds = ["pnpm prisma generate", "pnpm build"]

[start]
cmd = "pnpm prisma db push --accept-data-loss && pnpm start"
